### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by cmacdonnacha** [nickaranz/slackapi-angularjs#1]
Any chance you could add this to bower? 

Thanks,
Cathal.

**Comment by komagata** [comment]
+1

**Comment by cmacdonnacha** [comment]
[Pull](https://github.com/nickaranz/slackapi-angularjs/pull/4) request created for this

**Comment by nickaranz** [comment]
request merged. It'll soon be available to Bower.

**Comment by cmacdonnacha** [comment]
This package has now been added to [bower](http://bower.io/search/?q=slackapi-angularjs).
You can install it by running `bower install --save-dev slackapi-angularjs`

**Comment by cmacdonnacha** [comment]
Thanks for merging that in @nickaranz. I'm just wondering what you use to generate the **"build"** folder? You'll have to do this every time changes are made to the files within the **"src"** folder. Otherwise people will be using the older version.
