### ISSUE TITLE
Examples / documentation?

### ISSUE THREAD

**Issue by goldylucks** [nickaranz/slackapi-angularjs#3]
I don't understand the basic setup from the documentation :/

Where do I configure the token?

Do u hav a project maybe where u use this service?

I will glady write a better documentation if I could get this to work :)

**Comment by nickaranz** [comment]
Hi Adam, thanks for reaching out. I dont have a public project where this service is being utilized. 

Regarding your question, you can get a Slack Token from this link: https://api.slack.com/web (you will need to be logged-in ) scroll down to the 'Authentication' section. Now, from the build code here : https://github.com/nickaranz/slackapi-angularjs/blob/master/build/ng-deg.slackapi.js you can copy paste that token under the DefaultToken property.

Best
