### ISSUE TITLE
Posting message doesn't work in build version

### ISSUE THREAD

**Issue by J-Graham** [nickaranz/slackapi-angularjs#7]
I noticed that in both build versions of the application when you call slackSvc.chat.postMessage it is not calling the correct API method.  It calls a method that will return channel info.  I've corrected it in both versions and will submit a pull request, but just wanted to open an issue for tracking purposes.

```
 // CHAT
        function postMessage(channeId, message, callback, token) {
            var params = {
                token: token || slackConfig.DefaultToken,
                channel: channeId,
                text: message
            };
            executeApiCall("channels.info", params, callback);
        }
```

**Comment by nickaranz** [comment]
Thank you for fixing the method call, I have merged your pull request!
